#!/bin/sh
# rename all the files
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 1*_t01.mkv "Looney Tunes - S1946E02 - Baseball Bugs.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 1*_t02.mkv "Looney Tunes - S1952E23 - Rabbit Seasoning.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 1*_t03.mkv "Looney Tunes - S1949E16 - Long-Haired Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 1*_t04.mkv "Looney Tunes - S1949E11 - High Diving Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 1*_t05.mkv "Looney Tunes - S1953E19 - Bully for Bugs.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 1*_t06.mkv "Looney Tunes - S1950E15 - What's Up Doc_.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 1*_t07.mkv "Looney Tunes - S1952E27 - Rabbit's Kin.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 1*_t08.mkv "Looney Tunes - S1952E11 - Water, Water Every Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 1*_t09.mkv "Looney Tunes - S1950E10 - Big House Bunny.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 1*_t10.mkv "Looney Tunes - S1951E27 - Big Top Bunny.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 1*_t11.mkv "Looney Tunes - S1948E32 - My Bunny Lies over the Sea.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 1*_t12.mkv "Looney Tunes - S1941E40 - Wabbit Twouble.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 1*_t13.mkv "Looney Tunes - S1951E23 - Ballot Box Bunny.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 1*_t14.mkv "Looney Tunes - S1950E30 - Rabbit of Seville.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 2*_t01.mkv "Looney Tunes - S1953E06 - Duck Amuck.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 2*_t02.mkv "Looney Tunes - S1949E23 - Dough for the Do-Do.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 2*_t03.mkv "Looney Tunes - S1951E26 - Drip-Along Daffy.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 2*_t04.mkv "Looney Tunes - S1948E33 - Scaredy Cat.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 2*_t05.mkv "Looney Tunes - S1950E21 - The Ducksters.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 2*_t06.mkv "Looney Tunes - S1950E06 - The Scarlet Pumpernickel.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 2*_t07.mkv "Looney Tunes - S1943E14 - Yankee Doodle Daffy.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 2*_t08.mkv "Looney Tunes - S1949E05 - Porky Chops.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 2*_t09.mkv "Looney Tunes - S1951E17 - The Wearing of the Grin.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 2*_t10.mkv "Looney Tunes - S1956E23 - Deduce, You Say.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 2*_t11.mkv "Looney Tunes - S1950E03 - Boobs in the Woods.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 2*_t12.mkv "Looney Tunes - S1950E18 - Golden Yeggs.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 2*_t13.mkv "Looney Tunes - S1951E13 - Rabbit Fire.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 2*_t14.mkv "Looney Tunes - S1953E18 - Duck Dodgers in the 24th Century.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 3*_t01.mkv "Looney Tunes - S1940E07 - Elmer's Candid Camera.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 3*_t02.mkv "Looney Tunes - S1944E05 - Bugs Bunny and the Three Bears.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 3*_t03.mkv "Looney Tunes - S1949E24 - Fast and Furry-ous.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 3*_t04.mkv "Looney Tunes - S1946E10 - Hair-Raising Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 3*_t05.mkv "Looney Tunes - S1949E04 - Awful Orphan.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 3*_t06.mkv "Looney Tunes - S1948E19 - Haredevil Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 3*_t07.mkv "Looney Tunes - S1949E29 - For Scent-imental Reasons.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 3*_t08.mkv "Looney Tunes - S1949E26 - Frigid Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 3*_t09.mkv "Looney Tunes - S1950E09 - The Hypo-Chondri-Cat.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 3*_t10.mkv "Looney Tunes - S1959E01 - Baton Bunny.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 3*_t11.mkv "Looney Tunes - S1952E03 - Feed the Kitty.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 3*_t12.mkv "Looney Tunes - S1953E01 - Don't Give Up the Sheep.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 3*_t13.mkv "Looney Tunes - S1942E22 - Bugs Bunny Gets the Boid.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 3*_t14.mkv "Looney Tunes - S1943E04 - Tortoise Wins by a Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 4*_t01.mkv "Looney Tunes - S1950E24 - Canary Row.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 4*_t02.mkv "Looney Tunes - S1950E23 - Bunker Hill Bunny.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 4*_t03.mkv "Looney Tunes - S1948E29 - Kit for Cat.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 4*_t04.mkv "Looney Tunes - S1951E05 - Putty Tat Trouble.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 4*_t05.mkv "Looney Tunes - S1954E07 - Bugs and Thugs.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 4*_t06.mkv "Looney Tunes - S1951E03 - Canned Feud.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 4*_t07.mkv "Looney Tunes - S1955E16 - Lumber Jerks.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 4*_t08.mkv "Looney Tunes - S1955E23 - Speedy Gonzales.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 4*_t09.mkv "Looney Tunes - S1951E22 - Tweety's S.O.S..mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 4*_t10.mkv "Looney Tunes - S1948E26 - The Foghorn Leghorn.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 4*_t11.mkv "Looney Tunes - S1949E08 - Daffy Duck Hunt.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 4*_t12.mkv "Looney Tunes - S1951E12 - Early to Bet.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 4*_t13.mkv "Looney Tunes - S1959E18 - A Broken Leghorn.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ DISC\ 4*_t14.mkv "Looney Tunes - S1954E15 - Devil May Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 1*_t01.mkv "Looney Tunes - S1946E21 - The Big Snooze.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 1*_t02.mkv "Looney Tunes - S1956E05 - Broom-Stick Bunny.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 1*_t03.mkv "Looney Tunes - S1948E15 - Bugs Bunny Rides Again.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 1*_t04.mkv "Looney Tunes - S1951E07 - Bunny Hugged.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 1*_t05.mkv "Looney Tunes - S1951E16 - Fmvch Rarebit.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 1*_t06.mkv "Looney Tunes - S1948E01 - Gorilla My Dreams.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 1*_t07.mkv "Looney Tunes - S1942E35 - The Hare-Brained Hypnotist.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 1*_t08.mkv "Looney Tunes - S1945E13 - Hare Conditioned.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 1*_t09.mkv "Looney Tunes - S1941E23 - The Heckling Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 1*_t10.mkv "Looney Tunes - S1944E01 - Little Red Riding Rabbit.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 1*_t11.mkv "Looney Tunes - S1941E09 - Tortoise Beats Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 1*_t12.mkv "Looney Tunes - S1947E08 - Rabbit Transit.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 1*_t13.mkv "Looney Tunes - S1947E19 - Slick Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 1*_t14.mkv "Looney Tunes - S1954E30 - Baby Buggy Bunny.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 1*_t15.mkv "Looney Tunes - S1955E21 - Hyde and Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 2*_t01.mkv "Looney Tunes - S1952E08 - Beep Beep.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 2*_t02.mkv "Looney Tunes - S1952E12 - Going! Going! Gosh!.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 2*_t03.mkv "Looney Tunes - S1953E23 - Zipping Along.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 2*_t04.mkv "Looney Tunes - S1954E20 - Stop! Look! and Hasten!.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 2*_t05.mkv "Looney Tunes - S1955E11 - Ready.. Set.. Zoom!.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 2*_t06.mkv "Looney Tunes - S1955E29 - Guided Muscle.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 2*_t07.mkv "Looney Tunes - S1956E11 - Gee Whiz-z-z-z-z-z-z.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 2*_t08.mkv "Looney Tunes - S1956E26 - There They GO-GO-GO!.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 2*_t09.mkv "Looney Tunes - S1957E03 - Scrambled Aches.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 2*_t10.mkv "Looney Tunes - S1957E19 - Zoom and Bored.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 2*_t11.mkv "Looney Tunes - S1958E07 - Whoa, Be-Gone!.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 2*_t12.mkv "Looney Tunes - S1951E20 - Cheese Chasers.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 2*_t13.mkv "Looney Tunes - S1942E31 - The Dover Boys.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 2*_t14.mkv "Looney Tunes - S1949E10 - Mouse Wreckers.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 2*_t15.mkv "Looney Tunes - S1951E24 - A Bear for Punishment.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 3*_t01.mkv "Looney Tunes - S1949E19 - Bad Ol' Putty Tat.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 3*_t02.mkv "Looney Tunes - S1950E16 - All A Bir-r-r-d.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 3*_t03.mkv "Looney Tunes - S1951E14 - Room and Bird.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 3*_t04.mkv "Looney Tunes - S1951E28 - Tweet Tweet Tweety.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 3*_t05.mkv "Looney Tunes - S1952E04 - Gift Wrapped.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 3*_t06.mkv "Looney Tunes - S1952E16 - Ain't She Tweet.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 3*_t07.mkv "Looney Tunes - S1952E21 - A Bird in a Guilty Cage.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 3*_t08.mkv "Looney Tunes - S1953E02 - Snow Business.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 3*_t09.mkv "Looney Tunes - S1947E07 - Tweetie Pie.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 3*_t10.mkv "Looney Tunes - S1946E11 - Kitty Kornered.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 3*_t11.mkv "Looney Tunes - S1946E05 - Baby Bottleneck.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 3*_t12.mkv "Looney Tunes - S1939E22 - Old Glory.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 3*_t13.mkv "Looney Tunes - S1946E15 - The Great Piggy Bank Robbery.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 3*_t14.mkv "Looney Tunes - S1944E12 - Duck Soup to Nuts.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 3*_t15.mkv "Looney Tunes - S1938E29 - Porky in Wackyland.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 4*_t01.mkv "Looney Tunes - S1948E08 - Back Alley Oproar.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 4*_t02.mkv "Looney Tunes - S1946E01 - Book Revue.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 4*_t03.mkv "Looney Tunes - S1943E22 - A Corny Concerto.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 4*_t04.mkv "Looney Tunes - S1938E19 - Have You Got Any Castles_.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 4*_t05.mkv "Looney Tunes - S1941E17 - Hollywood Steps Out.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 4*_t06.mkv "Looney Tunes - S1936E19 - I Love to Singa.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 4*_t07.mkv "Looney Tunes - S1938E17 - Katnip Kollege.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 4*_t08.mkv "Looney Tunes - S1942E32 - The Hep Cat.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 4*_t09.mkv "Looney Tunes - S1957E01 - Three Little Bops.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 4*_t10.mkv "Looney Tunes - S1955E31 - One Froggy Evening.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 4*_t11.mkv "Looney Tunes - S1946E24 - Rhapsody Rabbit.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 4*_t12.mkv "Looney Tunes - S1957E22 - Show Biz Bugs.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 4*_t13.mkv "Looney Tunes - S1944E27 - Stage Door Cartoon.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 4*_t14.mkv "Looney Tunes - S1957E14 - What's Opera, Doc_.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ 2 DISC\ 4*_t15.mkv "Looney Tunes - S1940E16 - You Ought to Be in Pictures.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 1*_t01.mkv "Looney Tunes - S1944E17 - Hare Force.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 1*_t02.mkv "Looney Tunes - S1946E06 - Hare Remover.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 1*_t03.mkv "Looney Tunes - S1945E17 - Hare Tonic.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 1*_t04.mkv "Looney Tunes - S1947E05 - A Hare Grows in Manhattan.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 1*_t05.mkv "Looney Tunes - S1947E12 - Easter Yeggs.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 1*_t06.mkv "Looney Tunes - S1942E09 - The Wabbit Who Came to Supper.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 1*_t07.mkv "Looney Tunes - S1949E14 - Bowery Bugs.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 1*_t08.mkv "Looney Tunes - S1950E07 - Homeless Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 1*_t09.mkv "Looney Tunes - S1942E39 - Case of the Missing Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 1*_t10.mkv "Looney Tunes - S1946E13 - Acrobatty Bunny.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 1*_t11.mkv "Looney Tunes - S1943E17 - Wackiki Wabbit.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 1*_t12.mkv "Looney Tunes - S1949E02 - Hare Do.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 1*_t13.mkv "Looney Tunes - S1949E09 - Rebel Rabbit.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 1*_t14.mkv "Looney Tunes - S1950E19 - Hillbilly Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 1*_t15.mkv "Looney Tunes - S1953E24 - Duck! Rabbit, Duck!.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 2*_t01.mkv "Looney Tunes - S1938E37 - Daffy Duck in Hollywood.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 2*_t02.mkv "Looney Tunes - S1935E20 - Hollywood Capers.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 2*_t03.mkv "Looney Tunes - S1936E30 - The CooCoo Nut Grove.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 2*_t04.mkv "Looney Tunes - S1937E04 - Porky's Road Race.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 2*_t05.mkv "Looney Tunes - S1937E34 - The Woods Are Full of Cuckoos.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 2*_t06.mkv "Looney Tunes - S1937E09 - She Was an Acrobat's Daughter.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 2*_t07.mkv "Looney Tunes - S1939E43 - The Film Fan.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 2*_t08.mkv "Looney Tunes - S1937E25 - Speaking of the Weather.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 2*_t09.mkv "Looney Tunes - S1939E15 - Thugs with Dirty Mugs.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 2*_t10.mkv "Looney Tunes - S1941E11 - Goofy Groceries.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 2*_t11.mkv "Looney Tunes - S1944E10 - Swooner Crooner.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 2*_t12.mkv "Looney Tunes - S1956E25 - Wideo Wabbit.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 2*_t13.mkv "Looney Tunes - S1956E28 - The Honey-Mousers.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 2*_t14.mkv "Looney Tunes - S1961E18 - The Last Hungry Cat.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 2*_t15.mkv "Looney Tunes - S1959E06 - The Mouse That Jack Built.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 3*_t01.mkv "Looney Tunes - S1935E04 - I Haven't Got a Hat.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 3*_t02.mkv "Looney Tunes - S1937E08 - Porky's Romance.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 3*_t03.mkv "Looney Tunes - S1938E18 - Porky's Party.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 3*_t04.mkv "Looney Tunes - S1938E33 - Porky in Egypt.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 3*_t05.mkv "Looney Tunes - S1939E14 - Porky and Teabiscuit.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 3*_t06.mkv "Looney Tunes - S1937E03 - Pigs Is Pigs.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 3*_t07.mkv "Looney Tunes - S1943E03 - Pigs in a Polka.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 3*_t08.mkv "Looney Tunes - S1943E18 - Porky Pig's Feat.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 3*_t09.mkv "Looney Tunes - S1948E06 - Daffy Duck Slept Here.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 3*_t10.mkv "Looney Tunes - S1949E28 - Bye, Bye Bluebeard.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 3*_t11.mkv "Looney Tunes - S1950E13 - An Egg Scramble.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 3*_t12.mkv "Looney Tunes - S1958E05 - Robin Hood Daffy.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 3*_t13.mkv "Looney Tunes - S1949E22 - The Windblown Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 3*_t14.mkv "Looney Tunes - S1954E13 - Claws For Alarm.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 3*_t15.mkv "Looney Tunes - S1956E06 - Rocket Squad.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 4*_t01.mkv "Looney Tunes - S1939E13 - Daffy Duck and the Dinosaur.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 4*_t02.mkv "Looney Tunes - S1943E09 - Super-Rabbit.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 4*_t03.mkv "Looney Tunes - S1938E01 - Daffy Duck & Egghead.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 4*_t04.mkv "Looney Tunes - S1945E10 - A Gruesome Twosome.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 4*_t05.mkv "Looney Tunes - S1945E03 - Draftee Daffy.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 4*_t06.mkv "Looney Tunes - S1943E24 - Falling Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 4*_t07.mkv "Looney Tunes - S1957E12 - Steal Wool.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 4*_t08.mkv "Looney Tunes - S1957E16 - Birds Anonymous.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 4*_t09.mkv "Looney Tunes - S1954E06 - No Barking.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 4*_t10.mkv "Looney Tunes - S1948E10 - Rabbit Punch.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 4*_t11.mkv "Looney Tunes - S1943E27 - An Itch in Time.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 4*_t12.mkv "Looney Tunes - S1945E01 - Odor-Able Kitty.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 4*_t13.mkv "Looney Tunes - S1946E18 - Walky Talky Hawky.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 4*_t14.mkv "Looney Tunes - S1957E24 - Gonzales' Tamales.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 3\ DISC\ 4*_t15.mkv "Looney Tunes - S1963E17 - To Beep or Not to Beep.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 1*_t01.mkv "Looney Tunes - S1955E27 - Roman Legion-Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 1*_t02.mkv "Looney Tunes - S1949E20 - The Grey Hounded Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 1*_t03.mkv "Looney Tunes - S1949E34 - Rabbit Hood.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 1*_t04.mkv "Looney Tunes - S1952E02 - Operation_ Rabbit.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 1*_t05.mkv "Looney Tunes - S1955E24 - Knight-Mare Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 1*_t06.mkv "Looney Tunes - S1953E11 - Southern Fried Rabbit.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 1*_t07.mkv "Looney Tunes - S1949E06 - Mississippi Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 1*_t08.mkv "Looney Tunes - S1950E02 - Hurdy-Gurdy Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 1*_t09.mkv "Looney Tunes - S1953E04 - Forward March Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 1*_t10.mkv "Looney Tunes - S1955E08 - Sahara Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 1*_t11.mkv "Looney Tunes - S1956E17 - Barbary-Coast Bunny.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 1*_t12.mkv "Looney Tunes - S1956E29 - To Hare is Human.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 1*_t13.mkv "Looney Tunes - S1950E14 - 8 Ball Bunny.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 1*_t14.mkv "Looney Tunes - S1958E13 - Knighty Knight Bugs.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 1*_t15.mkv "Looney Tunes - S1957E25 - Rabbit Romeo.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 2*_t01.mkv "Looney Tunes - S1937E31 - The Case of the Stuttering Pig.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 2*_t02.mkv "Looney Tunes - S1938E30 - Little Pancho Vanilla.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 2*_t03.mkv "Looney Tunes - S1936E29 - Little Beau Porky.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 2*_t04.mkv "Looney Tunes - S1938E13 - Now That Summer Is Gone.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 2*_t05.mkv "Looney Tunes - S1936E32 - Porky in the North Woods.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 2*_t06.mkv "Looney Tunes - S1938E34 - You're an Education.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 2*_t07.mkv "Looney Tunes - S1937E22 - Porky's Railroad.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 2*_t08.mkv "Looney Tunes - S1944E22 - Plane Daffy.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 2*_t09.mkv "Looney Tunes - S1938E16 - Porky the Fireman.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 2*_t10.mkv "Looney Tunes - S1938E27 - Cracked Ice.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 2*_t11.mkv "Looney Tunes - S1943E28 - Puss N' Booty.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 2*_t12.mkv "Looney Tunes - S1944E06 - I Got Plenty of Mutton.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 2*_t13.mkv "Looney Tunes - S1944E24 - Booby Hatched.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 2*_t14.mkv "Looney Tunes - S1936E22 - Porky's Poultry Plant.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 2*_t15.mkv "Looney Tunes - S1944E26 - The Stupid Cupid.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 3*_t01.mkv "Looney Tunes - S1953E21 - Cat-Tails For Two.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 3*_t02.mkv "Looney Tunes - S1957E15 - Tabasco Road.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 3*_t03.mkv "Looney Tunes - S1958E02 - Tortilla Flaps.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 3*_t04.mkv "Looney Tunes - S1959E12 - Mexicali Shmoes.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 3*_t05.mkv "Looney Tunes - S1959E16 - Here Today, Gone Tamale.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 3*_t06.mkv "Looney Tunes - S1960E02 - West of the Pesos.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 3*_t07.mkv "Looney Tunes - S1961E01 - Cannery Woe.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 3*_t08.mkv "Looney Tunes - S1961E13 - The Pied Piper of Guadalupe.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 3*_t09.mkv "Looney Tunes - S1962E06 - Mexican Boarders.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 3*_t10.mkv "Looney Tunes - S1963E11 - Chili Weather.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 3*_t11.mkv "Looney Tunes - S1964E02 - A Message To Gracias.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 3*_t12.mkv "Looney Tunes - S1964E06 - Nuts and Volts.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 3*_t13.mkv "Looney Tunes - S1964E12 - Pancho's Hideaway.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 3*_t14.mkv "Looney Tunes - S1965E05 - The Wild Chase.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 3*_t15.mkv "Looney Tunes - S1966E09 - A-Haunting We Will Go.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 4*_t01.mkv "Looney Tunes - S1938E35 - The Night Watchman.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 4*_t02.mkv "Looney Tunes - S1942E07 - Conrad the Sailor.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 4*_t03.mkv "Looney Tunes - S1940E34 - The Sour Puss.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 4*_t04.mkv "Looney Tunes - S1943E16 - The Aristo-Cat.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 4*_t05.mkv "Looney Tunes - S1948E21 - Dough Ray Me-ow.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 4*_t06.mkv "Looney Tunes - S1955E01 - Pizzicato Pussycat.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 4*_t07.mkv "Looney Tunes - S1953E05 - Kiss Me Cat.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 4*_t08.mkv "Looney Tunes - S1958E20 - Cat Feud.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 4*_t09.mkv "Looney Tunes - S1956E13 - The Unexpected Pest.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 4*_t10.mkv "Looney Tunes - S1957E05 - Go Fly a Kit.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 4*_t11.mkv "Looney Tunes - S1952E10 - Kiddin' the Kitten.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 4*_t12.mkv "Looney Tunes - S1953E08 - A Peck O' Trouble.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 4*_t13.mkv "Looney Tunes - S1960E11 - Mouse and Garden.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 4*_t14.mkv "Looney Tunes - S1940E13 - Porky's Poor Fish.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 4\ DISC\ 4*_t15.mkv "Looney Tunes - S1949E27 - Swallow the Leader.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 1*_t01.mkv "Looney Tunes - S1952E07 - 14 Carrot Rabbit.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 1*_t02.mkv "Looney Tunes - S1957E04 - Ali Baba Bunny.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 1*_t03.mkv "Looney Tunes - S1948E13 - Buccaneer Bunny.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 1*_t04.mkv "Looney Tunes - S1956E01 - Bugs' Bonnets.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 1*_t05.mkv "Looney Tunes - S1956E22 - A Star is Bored.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 1*_t06.mkv "Looney Tunes - S1947E14 - A Pest in the House.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 1*_t07.mkv "Looney Tunes - S1963E16 - Transylvania 6-5000.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 1*_t08.mkv "Looney Tunes - S1952E17 - Oily Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 1*_t09.mkv "Looney Tunes - S1956E16 - Stupor Duck.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 1*_t10.mkv "Looney Tunes - S1948E30 - The Stupor Salesman.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 1*_t11.mkv "Looney Tunes - S1961E08 - The Abominable Snow Rabbit.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 1*_t12.mkv "Looney Tunes - S1952E26 - The Super Snooper.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 1*_t13.mkv "Looney Tunes - S1948E17 - The Up-Standing Sitter.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 1*_t14.mkv "Looney Tunes - S1946E12 - Hollywood Daffy.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 1*_t15.mkv "Looney Tunes - S1948E20 - You Were Never Duckier.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 2*_t01.mkv "Looney Tunes - S1954E18 - Bewitched Bunny.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 2*_t02.mkv "Looney Tunes - S1949E07 - Paying the Piper.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 2*_t03.mkv "Looney Tunes - S1940E11 - The Bear's Tale.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 2*_t04.mkv "Looney Tunes - S1942E24 - Foney Fables.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 2*_t05.mkv "Looney Tunes - S1960E05 - Goldimouse and the Three Cats.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 2*_t06.mkv "Looney Tunes - S1946E03 - Holiday for Shoestrings.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 2*_t07.mkv "Looney Tunes - S1952E13 - Little Red Rodent Hood.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 2*_t08.mkv "Looney Tunes - S1937E32 - Little Red Walking Hood.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 2*_t09.mkv "Looney Tunes - S1955E26 - Red Riding Hoodwinked.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 2*_t10.mkv "Looney Tunes - S1941E14 - The Trial of Mr. Wolf.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 2*_t11.mkv "Looney Tunes - S1952E18 - The Turn-Tale Wolf.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 2*_t12.mkv "Looney Tunes - S1940E18 - Tom Thumb in Trouble.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 2*_t13.mkv "Looney Tunes - S1957E10 - Tweety and the Beanstalk.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 2*_t14.mkv "Looney Tunes - S1940E17 - A Gander at Mother Goose.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 2*_t15.mkv "Looney Tunes - S1964E11 - Senorella And The Glass Huarache.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 3*_t01.mkv "Looney Tunes - S1946E16 - Bacall to Arms.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 3*_t02.mkv "Looney Tunes - S1944E20 - Buckaroo Bugs.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 3*_t03.mkv "Looney Tunes - S1942E08 - Crazy Cruise.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 3*_t04.mkv "Looney Tunes - S1941E16 - Farm Frolics.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 3*_t05.mkv "Looney Tunes - S1944E15 - Hare Ribbin'.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 3*_t06.mkv "Looney Tunes - S1940E26 - Patient Porky.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 3*_t07.mkv "Looney Tunes - S1940E31 - Prehistoric Porky.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 3*_t08.mkv "Looney Tunes - S1945E15 - The Bashful Buzzard.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 3*_t09.mkv "Looney Tunes - S1944E25 - The Old Grey Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 3*_t10.mkv "Looney Tunes - S1942E14 - The Wacky Wabbit.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 3*_t11.mkv "Looney Tunes - S1943E11 - The Wise Quacking Duck.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 3*_t12.mkv "Looney Tunes - S1945E12 - Wagon Heels.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 3*_t13.mkv "Looney Tunes - S1938E36 - The Daffy Doc.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 3*_t14.mkv "Looney Tunes - S1942E36 - A Tale of Two Kitties.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 3*_t15.mkv "Looney Tunes - S1941E41 - Porky's Pooch.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 4*_t01.mkv "Looney Tunes - S1936E06 - Alpine Antics.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 4*_t02.mkv "Looney Tunes - S1942E28 - Eatin' on the Cuff or The Moth Who Came to Dinner.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 4*_t03.mkv "Looney Tunes - S1936E26 - Milk and Money.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 4*_t04.mkv "Looney Tunes - S1933E19 - I've Got to Sing a Torch Song.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 4*_t05.mkv "Looney Tunes - S1938E04 - Porky at the Crocadero.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 4*_t06.mkv "Looney Tunes - S1939E19 - Polar Pals.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 4*_t07.mkv "Looney Tunes - S1943E20 - Scrap Happy Daffy.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 4*_t08.mkv "Looney Tunes - S1937E33 - Porky's Double Trouble.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 4*_t09.mkv "Looney Tunes - S1935E21 - Gold Diggers of '49.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 4*_t10.mkv "Looney Tunes - S1940E08 - Pilgrim Porky.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 4*_t11.mkv "Looney Tunes - S1939E26 - Wise Quacks.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 4*_t12.mkv "Looney Tunes - S1941E13 - Porky's Preview.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 4*_t13.mkv "Looney Tunes - S1938E02 - Porky's Poppa.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 4*_t14.mkv "Looney Tunes - S1938E25 - Wholly Smoke.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 5\ DISC\ 4*_t15.mkv "Looney Tunes - S1938E06 - What Price Porky.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 1*_t01.mkv "Looney Tunes - S1945E08 - Hare Trigger.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 1*_t02.mkv "Looney Tunes - S1943E05 - To Duck or Not to Duck.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 1*_t03.mkv "Looney Tunes - S1947E06 - Birth of a Notion.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 1*_t04.mkv "Looney Tunes - S1954E28 - My Little Duckaroo.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 1*_t05.mkv "Looney Tunes - S1947E13 - Crowing Pains.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 1*_t06.mkv "Looney Tunes - S1956E20 - Raw! Raw! Rooster.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 1*_t07.mkv "Looney Tunes - S1956E08 - Heaven Scent.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 1*_t08.mkv "Looney Tunes - S1942E38 - My Favorite Duck.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 1*_t09.mkv "Looney Tunes - S1955E19 - Jumpin' Jupiter.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 1*_t10.mkv "Looney Tunes - S1954E19 - Satan's Waitin'.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 1*_t11.mkv "Looney Tunes - S1958E16 - Hook, Line, and Stinker.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 1*_t12.mkv "Looney Tunes - S1949E32 - Bear Feat.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 1*_t13.mkv "Looney Tunes - S1950E20 - Dog Gone South.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 1*_t14.mkv "Looney Tunes - S1949E33 - A Ham in a Role.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 1*_t15.mkv "Looney Tunes - S1949E21 - Often an Orphan.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 2*_t01.mkv "Looney Tunes - S1945E02 - Herr Meets Hare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 2*_t02.mkv "Looney Tunes - S1944E11 - Russian Rhapsody.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 2*_t03.mkv "Looney Tunes - S1943E26 - Daffy- The Commando.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 2*_t04.mkv "Looney Tunes - S1931E12 - Bosko the Doughboy.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 2*_t05.mkv "Looney Tunes - S1941E35 - Rookie Revue.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 2*_t06.mkv "Looney Tunes - S1942E15 - The Draft Horse.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 2*_t07.mkv "Looney Tunes - S1942E23 - Wacky Blackout.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 2*_t08.mkv "Looney Tunes - S1942E25 - The Ducktators.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 2*_t09.mkv "Looney Tunes - S1944E07 - The Weakly Reporter.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 2*_t10.mkv "Looney Tunes - S1943E06 - The Fifth-Column Mouse.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 2*_t11.mkv "Looney Tunes - S1941E22 - Meet John Doughboy.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 2*_t12.mkv "Looney Tunes - S1946E08 - Hollywood Canine Canteen.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 2*_t13.mkv "Looney Tunes - S1954E24 - By Word of Mouse.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 2*_t14.mkv "Looney Tunes - S1955E28 - Heir-Conditioned.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 2*_t15.mkv "Looney Tunes - S1956E24 - Yankee Dood It.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 3*_t01.mkv "Looney Tunes - S1930E02 - Congo Jazz.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 3*_t02.mkv "Looney Tunes - S1931E09 - Smile, Darn Ya, Smile!.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 3*_t03.mkv "Looney Tunes - S1930E04 - The Booze Hangs High.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 3*_t04.mkv "Looney Tunes - S1931E11 - One More Time.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 3*_t05.mkv "Looney Tunes - S1933E16 - Bosko's Picture Show.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 3*_t06.mkv "Looney Tunes - S1931E13 - You Don't Know What You're Doin'!.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 3*_t07.mkv "Looney Tunes - S1933E15 - We're in the Money.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 3*_t08.mkv "Looney Tunes - S1932E20 - Ride Him, Bosko!.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 3*_t09.mkv "Looney Tunes - S1933E13 - Shuffle Off to Buffalo.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 3*_t10.mkv "Looney Tunes - S1933E04 - Bosko in Person.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 3*_t11.mkv "Looney Tunes - S1933E14 - The Dish Ran Away with the Spoon.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 3*_t12.mkv "Looney Tunes - S1933E17 - Buddy's Day Out.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 3*_t13.mkv "Looney Tunes - S1933E21 - Buddy's Beer Garden.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 3*_t14.mkv "Looney Tunes - S1934E20 - Buddy's Circus.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 3*_t15.mkv "Looney Tunes - S1935E18 - A Cartoonist's Nightmare.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 4*_t01.mkv "Looney Tunes - S1942E11 - Horton Hatches the Egg.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 4*_t02.mkv "Looney Tunes - S1942E16 - Lights Fantastic.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 4*_t03.mkv "Looney Tunes - S1945E14 - Fresh Airedale.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 4*_t04.mkv "Looney Tunes - S1951E15 - Chow Hound.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 4*_t05.mkv "Looney Tunes - S1954E17 - The Oily American.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 4*_t06.mkv "Looney Tunes - S1950E17 - It's Hummer Time.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 4*_t07.mkv "Looney Tunes - S1956E18 - Rocket-Bye Baby.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 4*_t08.mkv "Looney Tunes - S1954E23 - Goo Goo Goliath.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 4*_t09.mkv "Looney Tunes - S1954E05 - Wild Wife.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 4*_t10.mkv "Looney Tunes - S1953E13 - Much Ado About Nutting.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 4*_t11.mkv "Looney Tunes - S1955E10 - The Hole Idea.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 4*_t12.mkv "Looney Tunes - S1963E06 - Now Hear This.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 4*_t13.mkv "Looney Tunes - S1962E17 - Martian Through Georgia.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 4*_t14.mkv "Looney Tunes - S1936E05 - Page Miss Glory.mkv"
mv LOONEY\ TUNES\ GOLDEN\ COLLECTION\ VOLUME\ 6\ DISC\ 4*_t15.mkv "Looney Tunes - S1968E02 - Norman Normal.mkv"
